name: DevAthlon
main: com.vcam123.devathlon.DevAthlon
version: 1.0
commands:
    mirror:
        usage: /<command>
        description: Gives a two way mirror
    instructions:
        usage: /<command>
        description: Gives mirror instructions
    carpet:
        usage: /<command>
        description: Gives a flying carpet