name: DevAthlon
main: com.vcam123.devathlon.DevAthlon
version: 1.0
commands:
    mirror:
        usage: /<command>
        description: Admin command for testing
    instructions:
        usage: /<command>
        description: Gives mirror instructions